include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    close_sinks: true
    enable_null_safety: true
