name: ff_alarm
description: "Eine Alarmierungsapp für freiwillige Feuerwehren."
homepage: "de.jena.feuerwehr.app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  awesome_notifications: 0.9.2
  firebase_messaging: 14.7.20
  firebase_core: 2.27.1
  go_router: 13.2.0
  shared_preferences: 2.2.2
  path_provider: 2.1.2
  app_group_directory: 2.0.0
  dio: 5.4.1
  geolocator: 11.0.0
  permission_handler: 11.3.0
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  flutter_colored_print:
    path: ./packages/flutter_colored_print/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  isar_generator: 3.1.0+1
  build_runner: 2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/android/
    - assets/ios/